apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wordpress 
spec:
  containers:
  - image: wordpress:latest 
    imagePullPolicy: IfNotPresent
    name: wordpress
  - image: mysql:5.7.26
    imagePullPolicy: IfNotPresent
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD 
        value: "passw0rd"
