apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
