apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/demo.conf
          name: nginx-confd-volume
          subPath: demo.conf
      volumes:
      - configMap:
          items:
          - key: demo.conf
            path: demo.conf
          name: nginx-confd
        name: nginx-confd-volume
