apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wordpress
    type: mysql
  name: wordpress-mysql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wordpress
      type: mysql
  template:
    metadata:
      labels:
        app: wordpress
        type: mysql
    spec:
      containers:
      - image: mysql:5.7.26
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD 
            value: "passw0rd"
          - name: MYSQL_DATABASE
            value: "wordpress"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-mysql-pv-claim 
