apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-svc 
  labels:
    app: wordpress
    type: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    type: mysql
