apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc 
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30611
  selector:
    app: wordpress
  type: NodePort
