apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: monitor
    type: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000 
    nodePort: 30611
  selector:
    app: monitor
    type: grafana
  type: NodePort
